---
title: "handle_missing"
author: "Chen Tianhao"
date: "2023-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(echo = TRUE)
```

## load useful packages
```{r, }
# load the useful packages
library(dplyr)
library(plotly)
library(CBCgrps)
library(networkD3)
```


## import the data and then have a look

```{r}
raw_data = read.csv("outputs/raw_data.csv", encoding="UTF-8")
raw_data[raw_data==""] = NA # convert the null values to NA
```

have a look of the structure of dataframe
```{r}
raw_data = raw_data[,1:78]
raw_data %>% dim()
```

load the outcome variable
```{r}
l_outcome = readRDS("outputs/l_outcome.rds")
```


```{r}
blood_level = l_outcome[[1]]
blood_level %>% head(10)
```

考察中医治疗和贫血幅度是否恶化的关系
```{r}
treatment = raw_data$用药时间
outcome = blood_level$贫血幅度是否改善
```

```{r}
logistic_model = lm(outcome ~ treatment, family = "binomial")
```

## 使用mice包来处理缺失数据

先把软件包安装上然后跑一下范例代码。
```{r}
library(mice)
```


看看pattern
```{r}
md.pattern(raw_data)

```

```{r}
# multiple impute the missing values
imp = mice(raw_data, maxit = 2, m = 2, seed = 1)
```

```{r}
stripplot(imp, "白细胞", pch = 19, xlab = "Imputation number")
```

```{r}
fit <- with(imp, lm(blood_level["贫血幅度是否改善"] ~ raw_data["用药时间"]))
```


