---
title: "研究1"
output: html_document
date: "2023-02-09"
---

# 读入原始数据
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(echo = TRUE)
```

## load useful packages
```{r}
# load the useful packages
library(dplyr)
library(plotly)
library(CBCgrps)
library(networkD3)

library(PerformanceAnalytics)

##randomForest 包的随机森林
library(randomForest)

#使用 MASS 包 polr() 训练序数 logistic 回归，详情 ?polr
library(MASS)

library("ggpubr")
library(car)
library(multcomp)
```


## import the data and then have a look

```{r}
raw_data = read.csv("outputs/raw_data.csv", encoding="UTF-8")
raw_data[raw_data==""] = NA # convert the null values to NA
```

have a look of the structure of dataframe
```{r}
raw_data = raw_data[,1:78]
raw_data %>% dim()
```

# 读入数据探索给出的数据
```{r}

l_exploration_1 = readRDS("outputs/l_exploration_1.rds")
df_data_glm = l_exploration_1$df_data_glm
df_data_rf = l_exploration_1$df_data_rf
df_grpcop = l_exploration_1$df_grpcop
```

处理终点变量: 分成两种方法, 一种是分成三个有序的层次, 另一个是分成分位数
```{r}
df_data_glm %>% colnames()
```

## 将血红蛋白分成三个层次

-10<, 贫血状况为恶化, 变化在-10到10之间, 贫血状况为不变, >10, 贫血状况为改善
```{r}
df_data_glm["血红蛋白数值变化"] %>% boxplot()
```


```{r}
df_data_glm[df_data_glm["血红蛋白数值变化"]< -10, "贫血三分类"]=0 #23行
```


```{r}
df_data_glm[df_data_glm["血红蛋白数值变化"]> 10, "贫血三分类"]=2 #55行
```

```{r}
df_data_glm[(df_data_glm["血红蛋白数值变化"]<=10)&(df_data_glm["血红蛋白数值变化"]>=-10), "贫血三分类"]=1 #34行
```

```{r}
df_data_glm[, "贫血三分类"] %>% table()
```

搞成有序列的因子
```{r}
[, "贫血三分类"] = df_data_glm[, "贫血三分类"] %>% as.factor() %>% ordered()
df_data_glm %>% str()
```

单因素分析
```{r}
fit_贫血三分类与用药 = polr(贫血三分类 ~ 用药时间, data = df_data_glm)

summary(fit_贫血三分类与用药)  #展示拟合回归的简单统计
```


需要写一个读取的辅助函数
```{r}

get_glm_OR = function(fit_single_model, row_var=2) {
  # 参数: 
  # fit_single_model: glm模型
  # row_var: 第几个回归变量, 1为截距, 再单因素分析里面, 2为需要分析的因素
  # 返回: 
  # 一个vector, 有四个列, 第一列OR的点估计, 第二列是区间下限(2.5%), 第三列是
  # 区间上限(97,5%), 第四列是p值
  vec_coef_p = coefficients(summary.glm(fit_single_model))[row_var, c(1,4)]
  vec_cofint = confint(fit_single_model)[row_var,] 
  vec_est = c(vec_coef_p[1], vec_cofint, vec_coef_p[2])
  vec_est[1:3] = exp(vec_est[1:3])
  # vec_est = format(vec_est, scientific = FALSE, digits = 1)
  # vec_est = as.numeric(vec_est)
  return(vec_est)
}

# debug
vec_用药 = get_glm_OR(fit_血红蛋白与用药)
vec_用药 %>% print()
```



## for循环得到17个模型
尝试写一个for循环来解决问题
```{r}
var_单因素 = c("用药时间", "年龄", "bmi", "血红蛋白", "IL.6.0.7pg.ml.", "CRP", "淋巴细胞绝对值", "中性粒细胞绝对值", "中性粒.淋巴", "mchc", "IL.6.0.7pg.ml..1", "CRP.1", "淋巴细胞绝对值.1", "中性粒细胞绝对值.1", "中性粒.淋巴.1", "mchc.1")
```

```{r}
df_data_glm[, var_单因素] %>% head()
```

```{r}
# lapply(1:30, function(i) glm(as.formula(paste0('casecontrol ~ ', 'rs', i)), data = mydata, family = binomial))

l_单因素回归 = 
  lapply(var_单因素, 
         function(i) polr(as.formula(paste('贫血三分类 ~ ', i)), 
                          data = df_data_glm))
```


# 搞个方差分析, 先看看贫血基线值和分类
```{r}
df_data_glm$贫血三分类 %>% head() %>% print()
df_data_glm$血红蛋白 %>% head() %>% print()
```

```{r}
kruskal.test(贫血三分类~淋巴细胞绝对值.1, data = df_data_glm)

```

```{r}
# 搞一个差值的比较
df_data_glm[, "淋巴细胞绝对值之差"] =
  df_data_glm[, "淋巴细胞绝对值.1"] - df_data_glm[, "淋巴细胞绝对值"]

df_data_glm[, "淋巴细胞绝对值之差"] %>% summary()
```

```{r}
ggboxplot(data = df_data_glm, x = '贫血三分类', y = '淋巴细胞绝对值之差', color = '贫血三分类') +
stat_compare_means(method = 'wilcox.test', comparisons = list(c('0', '1'), c('0', '2'), c('1', '2')))

```

血红蛋白变化和贫血三分类的关系
```{r}
ggboxplot(data = df_data_glm, x = '贫血三分类', y = '血红蛋白变化值', color = '贫血三分类') +
stat_compare_means(method = 'wilcox.test', comparisons = list(c('0', '1'), c('0', '2'), c('1', '2')))

```


# 将含有贫血三分类的表格保存
```{r}
df_data_glm %>% write.csv("outputs/df_data_glm.csv", row.names = FALSE)
```


















